### ISSUE TITLE
请确认是否需要添加忽略。添加该代码后，该资源路径将不做Token验证

### ISSUE THREAD

**Issue by erdongritian** [zhangxinhang/Swagger2-RestEasy3#1]
你好，我看你在文件SwaggerRestEasyExample 中，写了一段注释，说可以添加忽略，请问一下怎么添加忽略？

**Comment by zhangxinhang** [comment]
哦，那个是忘记删除了，与该项目没有关系，只是从原有业务代码中抽离时忘了删除了。不好意思给你造成困扰了。
